version: 0.2

phases:
  install:
    commands:
      # Install kubectl for interacting with EKS
      - echo Installing kubectl...
      - curl -LO "https://dl.k8s.io/release/v1.27.0/bin/linux/amd64/kubectl"
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
      - export KUBECONFIG=$HOME/.kube/config

  pre_build:
    commands:
      # Log in to Amazon ECR
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 344101797155.dkr.ecr.ca-central-1.amazonaws.com/samplerepo
      - echo Building Docker image...
      - docker build -t sample-dotnet-app .
      # Tag the Docker image with the ECR repository URI
      - docker tag sample-dotnet-app:latest 344101797155.dkr.ecr.ca-central-1.amazonaws.com/samplerepo:latest

  post_build:
    commands:
       #- aws sts get-caller-identity --output text  # Verify assumed role
       # Push the Docker image to ECR
      - echo Pushing Docker image to ECR...
      - docker push 344101797155.dkr.ecr.ca-central-1.amazonaws.com/samplerepo:latest
      # Deploy the application to Kubernetes (EKS)
      - echo "Deploying to Kubernetes (EKS)..."
      - aws eks --region ca-central-1 update-kubeconfig --name democluster
      - kubectl apply -f k8s-deployment-service.yaml  
artifacts:
  files:
    - k8s-deployment-service.yaml
