version: 0.2

phases:
  install:
    commands:
          - echo Logging in to DockerHub...
  pre_build:
    commands:
      # Log in to Amazon ECR
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 344101797155.dkr.ecr.us-east-1.amazonaws.com/my-demo-repo
      - echo Building Docker image...
      - docker build -t sample-dotnet-app .
      # Tag the Docker image with the ECR repository URI
      - docker tag sample-dotnet-app:latest 344101797155.dkr.ecr.us-east-1.amazonaws.com/my-demo-repo:latest
  post_build:
    commands:
       # Push the Docker image to ECR
       - echo Pushing Docker image to ECR...
       - docker push 344101797155.dkr.ecr.us-east-1.amazonaws.com/my-demo-repo:latest
      - printf '[{"name":"'devcluster'","imageUri":"%s"}]' 344101797155.dkr.ecr.us-east-1.amazonaws.com/my-demo-repo:latest > imagedefinitions.json
artifacts:
    files: imagedefinitions.json








 
