apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  namespace: development # Added namespace here
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-container
        image: 344101797155.dkr.ecr.us-east-2.amazonaws.com/my-demo-repo:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: sample-service
  namespace: development # Added namespace here
spec:
  type: LoadBalancer
  selector:
    app: sample-app
  ports:
  - protocol: TCP
    port: 80       # External port
    targetPort: 80 # Port the container listens on
